const actionTypes = {
    SET_INPUT_MODE: 'SET_INPUT_MODE',
    SET_BEATS: 'SET_BEATS',
    SET_PITCH: 'SET_PITCH',
    ADD_TO_PITCH_OFFSET: 'ADD_TO_PITCH_OFFSET',
    SET_MODE: 'SET_MODE',
    INSERT_MEASURE: 'INSERT_MEASURE',
    ADD_CHORD: 'ADD_CHORD',
    SELECTION_LEFT: 'SELECTION_LEFT',
    SELECTION_RIGHT: 'SELECTION_RIGHT',
    SELECTION_UP: 'SELECTION_UP',
    SELECTION_DOWN: 'SELECTION_DOWN',
    DELETE_MEASURE: 'DELETE_MEASURE',
    DELETE_CHORD: 'DELETE_CHORD',
    START_EDITING: 'START_EDITING',
    STOP_EDITING: 'STOP_EDITING'
};

Object.freeze(actionTypes);

export default actionTypes;
